name: run tests

on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Setup gradlew execution permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test